// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMReP-ANm3-r3EZ3uArn4UhdEiPjZbaws',
    appId: '1:993016837191:web:0f8d02f14be3adfa3bed62',
    messagingSenderId: '993016837191',
    projectId: 'flutterfirebase-69b70',
    authDomain: 'flutterfirebase-69b70.firebaseapp.com',
    storageBucket: 'flutterfirebase-69b70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZZ2Bm7Hbt5SoqbSiR513wCluBaKyh6A',
    appId: '1:993016837191:android:2880f2370a4097713bed62',
    messagingSenderId: '993016837191',
    projectId: 'flutterfirebase-69b70',
    storageBucket: 'flutterfirebase-69b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3wiSiSukO9Y3oe6Kj39ZeuwMuG5ZRpvc',
    appId: '1:993016837191:ios:31e0c351656e3bae3bed62',
    messagingSenderId: '993016837191',
    projectId: 'flutterfirebase-69b70',
    storageBucket: 'flutterfirebase-69b70.appspot.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3wiSiSukO9Y3oe6Kj39ZeuwMuG5ZRpvc',
    appId: '1:993016837191:ios:53ff781903f8bb343bed62',
    messagingSenderId: '993016837191',
    projectId: 'flutterfirebase-69b70',
    storageBucket: 'flutterfirebase-69b70.appspot.com',
    iosBundleId: 'com.example.firebaseSetup.RunnerTests',
  );
}
